import {
  PROJETO_SECOES,
  SESSOES_VISAO_GERAL_SLUG,
  TITLE_KEY_TO_SECAO_SLUG,
} from "./secoes-projeto"

export { TITLE_KEY_TO_SECAO_SLUG }

export const TED_IDENTIFICACAO_SECAO_SLUGS = [
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROJETO,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROPOSTA,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_REPRESENTANTE_LEGAL,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_RESPONSAVEL_TECNICO,
] as const

export type TedIdentificacaoSecaoSlug =
  (typeof TED_IDENTIFICACAO_SECAO_SLUGS)[number]

/**
 * Seções do TED com fluxo de bloquear / marcar atenção.
 * Inclui Identificação + seções de Descrição já habilitadas.
 */
export const TED_SECOES_COM_REVIEW = [
  ...TED_IDENTIFICACAO_SECAO_SLUGS,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_JUSTIFICATIVA_MOTIVACAO,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_OBJETIVOS,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_METAS,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_ETAPAS_CRONOGRAMA,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_METODOLOGIA,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_RESULTADOS_ESPERADOS,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_GESTAO_PROJETO,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_HISTORICO_SITUACAO_TERRITORIO,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_BASE_TERRITORIAL,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_PUBLICO_BENEFICIARIO,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_POVOS_COMUNIDADES_TRADICIONAIS,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_PERFIL_SOCIO_OCUPACIONAL,
  PROJETO_SECOES.publicoBeneficiarioEServicos.slug,
  PROJETO_SECOES.outrasInformacoesProponente.slug,
  PROJETO_SECOES.valorTotal.slug,
  PROJETO_SECOES.cronogramaDesembolso.slug,
  PROJETO_SECOES.detalhamentoOrcamento.slug,
  PROJETO_SECOES.resumoPlanoAplicacao.slug,
  PROJETO_SECOES.procedimentosMonitoramento.slug,
  PROJETO_SECOES.indicadoresEficiencia.slug,
] as const

export type TedSecaoComReviewSlug = (typeof TED_SECOES_COM_REVIEW)[number]

/** Mapeia bloco PATCH identificação → slug de review. */
export const IDENTIFICACAO_BLOCO_TO_SECAO_SLUG: Record<string, string> = {
  projeto: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROJETO,
  proponente: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROPOSTA,
  representante:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_REPRESENTANTE_LEGAL,
  "responsavel-tecnico":
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_RESPONSAVEL_TECNICO,
}
