import { SESSOES_VISAO_GERAL_SLUG } from "./visao-geral"

export const TED_IDENTIFICACAO_SECAO_SLUGS = [
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROJETO,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROPOSTA,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_REPRESENTANTE_LEGAL,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_RESPONSAVEL_TECNICO,
] as const

export type TedIdentificacaoSecaoSlug =
  (typeof TED_IDENTIFICACAO_SECAO_SLUGS)[number]

/**
 * Seções do TED com fluxo de bloquear / marcar atenção.
 * Inclui Identificação + seções de Descrição já habilitadas.
 */
export const TED_SECOES_COM_REVIEW = [
  ...TED_IDENTIFICACAO_SECAO_SLUGS,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_JUSTIFICATIVA_MOTIVACAO,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_OBJETIVOS,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_METAS,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_ETAPAS_CRONOGRAMA,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_METODOLOGIA,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_RESULTADOS_ESPERADOS,
  SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_GESTAO_PROJETO,
] as const

export type TedSecaoComReviewSlug = (typeof TED_SECOES_COM_REVIEW)[number]

/** Mapeia chave de SESSOES_VISAO_GERAL_TITLE → slug da seção. */
export const TITLE_KEY_TO_SECAO_SLUG: Record<string, string> = {
  TITLE_SESSAO_DADOS_GERAIS_PROJETO:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_DADOS_GERAIS_PROJETO,
  TITLE_SESSAO_DETALHAMENTO_CURSOS:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_DETALHAMENTO_CURSOS,
  TITLE_SESSAO_DESPESAS_ETAPA_1_1:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_DESPESAS_ETAPA_1_1,
  TITLE_SESSAO_DESPESAS_ETAPA_1_2:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_DESPESAS_ETAPA_1_2,
  TITLE_SESSAO_DESPESAS_EVENTO_FINAL:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_DESPESAS_EVENTO_FINAL,
  TITLE_SESSAO_IDENTIFICACAO_PROJETO:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROJETO,
  TITLE_SESSAO_IDENTIFICACAO_PROPOSTA:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROPOSTA,
  TITLE_SESSAO_IDENTIFICACAO_REPRESENTANTE_LEGAL:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_REPRESENTANTE_LEGAL,
  TITLE_SESSAO_IDENTIFICACAO_RESPONSAVEL_TECNICO:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_RESPONSAVEL_TECNICO,
  TITLE_SESSAO_JUSTIFICATIVA_MOTIVACAO:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_JUSTIFICATIVA_MOTIVACAO,
  TITLE_SESSAO_OBJETIVOS: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_OBJETIVOS,
  TITLE_SESSAO_METAS: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_METAS,
  TITLE_SESSAO_ETAPAS_CRONOGRAMA:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_ETAPAS_CRONOGRAMA,
  TITLE_SESSAO_METODOLOGIA: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_METODOLOGIA,
  TITLE_SESSAO_RESULTADOS_ESPERADOS:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_RESULTADOS_ESPERADOS,
  TITLE_SESSAO_GESTAO_PROJETO:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_GESTAO_PROJETO,
  TITLE_SESSAO_HISTORICO_SITUACAO_TERRITORIO:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_HISTORICO_SITUACAO_TERRITORIO,
  TITLE_SESSAO_BASE_TERRITORIAL:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_BASE_TERRITORIAL,
  TITLE_SESSAO_PUBLICO_BENEFICIARIO:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_PUBLICO_BENEFICIARIO,
  TITLE_SESSAO_POVOS_COMUNIDADES_TRADICIONAIS:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_POVOS_COMUNIDADES_TRADICIONAIS,
  TITLE_SESSAO_PERFIL_SOCIO_OCUPACIONAL:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_PERFIL_SOCIO_OCUPACIONAL,
  TITLE_SESSAO_SERVICOS_ACESSADOS:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_SERVICOS_ACESSADOS,
  TITLE_SESSAO_OUTRAS_INFORMACOES_PROPOSTA:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_OUTRAS_INFORMACOES_PROPOSTA,
  TITLE_SESSAO_VALOR_TOTAL: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_VALOR_TOTAL,
  TITLE_SESSAO_CRONOGRAMA_DESENBOLSO:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_CRONOGRAMA_DESENBOLSO,
  TITLE_SESSAO_DETALHAMENTO_ORCAMENTO:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_DETALHAMENTO_ORCAMENTO,
  TITLE_SESSAO_RESUMO_PLANO_APLICACAO:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_RESUMO_PLANO_APLICACAO,
  TITLE_SESSAO_PROCEDIMENTOS_MONITORAMENTO:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_PROCEDIMENTOS_MONITORAMENTO,
  TITLE_SESSAO_INDICADORES_EFICIENCIA:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_INDICADORES_EFICIENCIA,
}

/** Mapeia bloco PATCH identificação → slug de review. */
export const IDENTIFICACAO_BLOCO_TO_SECAO_SLUG: Record<string, string> = {
  projeto: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROJETO,
  proponente: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROPOSTA,
  representante:
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_REPRESENTANTE_LEGAL,
  "responsavel-tecnico":
    SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_RESPONSAVEL_TECNICO,
}
