export const ADMIN_USERS_FORM = {
  createTitle: "Criar usuário",
  editTitle: "Editar usuário",
  viewTitle: "Visualizar usuário",
  createDescription: "Informe os dados para cadastrar um novo usuário.",
  editDescription: "Atualize os dados do usuário selecionado.",
  viewDescription: "Confira os dados do usuário selecionado.",
  fields: {
    nome: "Nome",
    email: "E-mail",
    tipo: "Tipo",
    perfil: "Perfil",
    roles: "Permissões",
    ativo: "Usuário ativo",
  },
  placeholders: {
    nome: "Ex.: Maria Silva",
    email: "Ex.: maria.silva@org.gov.br",
    tipo: "Selecione o tipo",
    perfil: "Selecione um perfil",
    roles: "Selecione uma permissão",
  },
  validation: {
    nome: "Informe o nome do usuário.",
    email: "Informe o e-mail do usuário.",
    emailInvalid: "Informe um e-mail válido.",
    tipo: "Informe o tipo do usuário.",
    perfil: "Selecione um perfil.",
    roles: "Selecione uma permissão.",
  },
  submitError: "Não foi possível salvar o usuário.",
  saving: "Salvando...",
  save: "Salvar usuário",
  saveChanges: "Salvar alterações",
  cancel: "Cancelar",
  close: "Fechar",
} as const
