export {
  ATTENTION_FIELD_CLASS,
  OUTRAS_INFORMACOES_IDS,
  OUTRAS_INFORMACOES_LABELS,
  OUTRAS_INFORMACOES_MAX_LENGTH,
  OUTRAS_INFORMACOES_PLACEHOLDERS,
  OUTRAS_INFORMACOES_TEXT,
  VIEW_MODE_FIELD_CLASS,
} from "./form"
