import {
  SESSOES_VISAO_GERAL_SLUG,
  SESSOES_VISAO_GERAL_TITLE,
} from "@/features/projeto/constants/visao-geral"

/** Seções do TRP exibidas na visão geral (ordem do documento). */
export const SECOES_VISAO_GERAL: { slug: string; title: string }[] = [
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROJETO,                title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_IDENTIFICACAO_PROJETO },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROPOSTA,               title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_IDENTIFICACAO_PROPOSTA },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_REPRESENTANTE_LEGAL,    title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_IDENTIFICACAO_REPRESENTANTE_LEGAL },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_RESPONSAVEL_TECNICO,    title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_IDENTIFICACAO_RESPONSAVEL_TECNICO },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_JUSTIFICATIVA_MOTIVACAO,              title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_JUSTIFICATIVA_MOTIVACAO },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_OBJETIVOS,                            title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_OBJETIVOS },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_METAS,                                title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_METAS },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_ETAPAS_CRONOGRAMA,                    title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_ETAPAS_CRONOGRAMA },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_METODOLOGIA,                          title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_METODOLOGIA },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_RESULTADOS_ESPERADOS,                 title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_RESULTADOS_ESPERADOS },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_GESTAO_PROJETO,                       title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_GESTAO_PROJETO },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_HISTORICO_SITUACAO_TERRITORIO,        title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_HISTORICO_SITUACAO_TERRITORIO },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_BASE_TERRITORIAL,                     title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_BASE_TERRITORIAL },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_PUBLICO_BENEFICIARIO,                 title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_PUBLICO_BENEFICIARIO },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_POVOS_COMUNIDADES_TRADICIONAIS,       title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_POVOS_COMUNIDADES_TRADICIONAIS },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_PERFIL_SOCIO_OCUPACIONAL,             title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_PERFIL_SOCIO_OCUPACIONAL },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_SERVICOS_ACESSADOS,                   title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_SERVICOS_ACESSADOS },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_OUTRAS_INFORMACOES_PROPOSTA,          title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_OUTRAS_INFORMACOES_PROPOSTA },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_VALOR_TOTAL,                          title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_VALOR_TOTAL },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_CRONOGRAMA_DESENBOLSO,                title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_CRONOGRAMA_DESENBOLSO },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_DETALHAMENTO_ORCAMENTO,               title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_DETALHAMENTO_ORCAMENTO },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_RESUMO_PLANO_APLICACAO,               title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_RESUMO_PLANO_APLICACAO },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_PROCEDIMENTOS_MONITORAMENTO,          title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_PROCEDIMENTOS_MONITORAMENTO },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_INDICADORES_EFICIENCIA,               title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_INDICADORES_EFICIENCIA },
  { slug: SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_OBSERVACOES,                          title: SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_OBSERVACOES },
]
