export const SESSOES_VISAO_GERAL_SLUG = {
  SLUG_SESSAO_IDENTIFICACAO_PROJETO: "identificacao-projeto",
  SLUG_SESSAO_IDENTIFICACAO_PROPOSTA: "identificacao-proponente",
  SLUG_SESSAO_IDENTIFICACAO_REPRESENTANTE_LEGAL: "identificacao-representante-legal",
  SLUG_SESSAO_IDENTIFICACAO_RESPONSAVEL_TECNICO: "identificacao-responsavel-tecnico",
  SLUG_SESSAO_JUSTIFICATIVA_MOTIVACAO: "justificativa",
  SLUG_SESSAO_OBJETIVOS: "objetivos",
  SLUG_SESSAO_METAS: "metas",
  SLUG_SESSAO_ETAPAS_CRONOGRAMA: "etapas-cronograma",
  SLUG_SESSAO_METODOLOGIA: "metodologia",
  SLUG_SESSAO_RESULTADOS_ESPERADOS: "resultados-esperados",
  SLUG_SESSAO_GESTAO_PROJETO: "gestao-projeto",
  SLUG_SESSAO_HISTORICO_SITUACAO_TERRITORIO: "historico-situacao-territorio",
  SLUG_SESSAO_BASE_TERRITORIAL: "base-territorial",
  SLUG_SESSAO_PUBLICO_BENEFICIARIO: "publico-beneficiario",
  SLUG_SESSAO_POVOS_COMUNIDADES_TRADICIONAIS: "povos-comunidades-tradicionais",
  SLUG_SESSAO_PERFIL_SOCIO_OCUPACIONAL: "perfil-socio-ocupacional",
  SLUG_SESSAO_SERVICOS_ACESSADOS: "servicos-acessados",
  SLUG_SESSAO_OUTRAS_INFORMACOES_PROPOSTA: "outras-informacoes-proponente",
  SLUG_SESSAO_VALOR_TOTAL: "valor-total",
  SLUG_SESSAO_CRONOGRAMA_DESENBOLSO: "cronograma-desembolso",
  SLUG_SESSAO_DETALHAMENTO_ORCAMENTO: "detalhamento-orcamento",
  SLUG_SESSAO_RESUMO_PLANO_APLICACAO: "resumo-plano-aplicacao",
  SLUG_SESSAO_PROCEDIMENTOS_MONITORAMENTO: "procedimentos-monitoramento",
  SLUG_SESSAO_INDICADORES_EFICIENCIA: "indicadores-eficiencia",
  SLUG_SESSAO_OBSERVACOES: "observacoes",
} as const

export const SESSOES_VISAO_GERAL_TITLE = {
  TITLE_SESSAO_IDENTIFICACAO_PROJETO : "1. Identificação do Projeto",
  TITLE_SESSAO_IDENTIFICACAO_PROPOSTA : "2. Identificação do(a) proponente",
  TITLE_SESSAO_IDENTIFICACAO_REPRESENTANTE_LEGAL : "3. Identificação do representante legal do(a) proponente",
  TITLE_SESSAO_IDENTIFICACAO_RESPONSAVEL_TECNICO : "4. Identificação do responsável técnico",
  TITLE_SESSAO_JUSTIFICATIVA_MOTIVACAO : "5. Justificativa e motivação para celebração do instrumento",
  TITLE_SESSAO_OBJETIVOS : "6. Objetivos",
  TITLE_SESSAO_METAS : "7. Metas",
  TITLE_SESSAO_ETAPAS_CRONOGRAMA : "8. Etapas e cronograma de execução",
  TITLE_SESSAO_METODOLOGIA : "9. Metodologia",
  TITLE_SESSAO_RESULTADOS_ESPERADOS : "10. Resultados esperados",
  TITLE_SESSAO_GESTAO_PROJETO : "11. Gestão do Projeto",
  TITLE_SESSAO_HISTORICO_SITUACAO_TERRITORIO : "12. Histórico e situação socioeconômica do território",
  TITLE_SESSAO_BASE_TERRITORIAL : "13. Detalhamento da base territorial do projeto",
  TITLE_SESSAO_PUBLICO_BENEFICIARIO : "14. Público beneficiário do projeto",
  TITLE_SESSAO_POVOS_COMUNIDADES_TRADICIONAIS : "15. Povos ou comunidades tradicionais",
  TITLE_SESSAO_PERFIL_SOCIO_OCUPACIONAL : "16. Perfil sócio-ocupacional do público beneficiário",
  TITLE_SESSAO_SERVICOS_ACESSADOS : "17. Serviços acessados pelo público beneficiário",
  TITLE_SESSAO_OUTRAS_INFORMACOES_PROPOSTA : "18. Outras informações sobre o(a) proponente",
  TITLE_SESSAO_VALOR_TOTAL : "19. Valor total do projeto",
  TITLE_SESSAO_CRONOGRAMA_DESENBOLSO : "20. Cronograma de desembolso",
  TITLE_SESSAO_DETALHAMENTO_ORCAMENTO : "21. Detalhamento do orçamento",
  TITLE_SESSAO_RESUMO_PLANO_APLICACAO : "22. Resumo do plano de aplicação",
  TITLE_SESSAO_PROCEDIMENTOS_MONITORAMENTO : "23. Procedimentos de monitoramento e avaliação",
  TITLE_SESSAO_INDICADORES_EFICIENCIA : "24. Indicadores de eficiência e eficácia",
  TITLE_SESSAO_OBSERVACOES : "Observações",
} as const

export const SECAO_SLUG_TO_TITLE: Record<string, string> = {
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROJETO]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_IDENTIFICACAO_PROJETO,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_PROPOSTA]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_IDENTIFICACAO_PROPOSTA,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_REPRESENTANTE_LEGAL]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_IDENTIFICACAO_REPRESENTANTE_LEGAL,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_IDENTIFICACAO_RESPONSAVEL_TECNICO]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_IDENTIFICACAO_RESPONSAVEL_TECNICO,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_JUSTIFICATIVA_MOTIVACAO]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_JUSTIFICATIVA_MOTIVACAO,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_OBJETIVOS]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_OBJETIVOS,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_METAS]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_METAS,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_ETAPAS_CRONOGRAMA]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_ETAPAS_CRONOGRAMA,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_METODOLOGIA]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_METODOLOGIA,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_RESULTADOS_ESPERADOS]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_RESULTADOS_ESPERADOS,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_GESTAO_PROJETO]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_GESTAO_PROJETO,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_HISTORICO_SITUACAO_TERRITORIO]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_HISTORICO_SITUACAO_TERRITORIO,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_BASE_TERRITORIAL]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_BASE_TERRITORIAL,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_PUBLICO_BENEFICIARIO]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_PUBLICO_BENEFICIARIO,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_POVOS_COMUNIDADES_TRADICIONAIS]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_POVOS_COMUNIDADES_TRADICIONAIS,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_PERFIL_SOCIO_OCUPACIONAL]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_PERFIL_SOCIO_OCUPACIONAL,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_SERVICOS_ACESSADOS]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_SERVICOS_ACESSADOS,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_OUTRAS_INFORMACOES_PROPOSTA]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_OUTRAS_INFORMACOES_PROPOSTA,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_VALOR_TOTAL]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_VALOR_TOTAL,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_CRONOGRAMA_DESENBOLSO]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_CRONOGRAMA_DESENBOLSO,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_DETALHAMENTO_ORCAMENTO]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_DETALHAMENTO_ORCAMENTO,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_RESUMO_PLANO_APLICACAO]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_RESUMO_PLANO_APLICACAO,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_PROCEDIMENTOS_MONITORAMENTO]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_PROCEDIMENTOS_MONITORAMENTO,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_INDICADORES_EFICIENCIA]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_INDICADORES_EFICIENCIA,
  [SESSOES_VISAO_GERAL_SLUG.SLUG_SESSAO_OBSERVACOES]:
    SESSOES_VISAO_GERAL_TITLE.TITLE_SESSAO_OBSERVACOES,
  "informacoes-projeto": "Informações do projeto",
  "andamento-projeto": "Andamento do projeto",
}

export const TITULO_VISAO_GERAL = "Visão geral do projeto"
export const DESCRICAO_VISAO_GERAL =
  "Confira o resumo do documento TRP e exporte em PDF."
export const TITULO_INFORMACOES_PROJETO = "Informações do projeto"
export const DESCRICAO_INFORMACOES_PROJETO =
  "Defina o status, os responsáveis e acompanhe o preenchimento das seções do TRP."
export const TITULO_DOCUMENTO_TRP = "TERMO DE REFERÊNCIA DE PROJETO - TRP (Portaria MDS nº 1.131, de 25 de novembro de 2025)"
