export {
  DESCRICAO_INFORMACOES_PROJETO,
  DESCRICAO_VISAO_GERAL,
  SECAO_SLUG_TO_TITLE,
  SESSOES_VISAO_GERAL_SLUG,
  SESSOES_VISAO_GERAL_SUBTITLE,
  SESSOES_VISAO_GERAL_TITLE,
  TITULO_DOCUMENTO_TRP,
  TITULO_INFORMACOES_PROJETO,
  TITULO_VISAO_GERAL,
} from "@/features/projeto/constants/ted/visao-geral"
